### ISSUE TITLE
安装fatal error:

### ISSUE THREAD

**Issue by Oliver-F1** [chaunsin/netease-cloud-music#1]
请问一下，这个错误该如何解决？
$ go install
# github.com/google/brotli/go/cbrotli
../../../go/pkg/mod/github.com/google/brotli/go/cbrotli@v0.0.0-20240715182736-39bcecf4559f/reader.go:13:10: fatal error: brotli/decode.h: No such file or directory
   13 | #include <brotli/decode.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by chaunsin** [comment]
> 请问一下，这个错误该如何解决？ $ go install
> 
> # github.com/google/brotli/go/cbrotli
> ../../../go/pkg/mod/github.com/google/brotli/go/[cbrotli@v0.0.0-20240715182736-39bcecf4559f](mailto:cbrotli@v0.0.0-20240715182736-39bcecf4559f)/reader.go:13:10: fatal error: brotli/decode.h: No such file or directory 13 | #include <brotli/decode.h> | ^~~~~~~~~~~~~~~~~ compilation terminated.

看下你的环境变量
```shell
go env CGO_ENABLED
```
是不是为0如果为0则设置如下
```shell
go env -w CGO_ENABLED=1
```
然后尝试编译一下看看

**Comment by Oliver-F1** [comment]
谢谢，不过还是报错，我等再换个系统试试。
![Uploading image.png…]()

**Comment by chaunsin** [comment]
> 谢谢，不过还是报错，我等再换个系统试试。 ![微信图片_20240820210305](https://private-user-images.githubusercontent.com/59132857/359486443-f082c338-d985-41ba-979d-765323dc7abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDgzNzEsIm5iZiI6MTcyNDIwODA3MSwicGF0aCI6Ii81OTEzMjg1Ny8zNTk0ODY0NDMtZjA4MmMzMzgtZDk4NS00MWJhLTk3OWQtNzY1MzIzZGM3YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAyNDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMGQzNTYwNWI1ZTAyZWI0NjdkOWI2YWM2YzMxNWI1MDExYzEyMWZmZjFkYzY2ZDQwNzg4NzBhYjc5MDg4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dlfpxk8OsGfTSK1s_lIdUa-9G2r-KWmYwmj9YmWMabU)

你编译采用的什么系统啊？

**Comment by eplt** [comment]
assuming you are using Apple Silicon Mac, you might need to do the following:

download and compile brotli from source, with "set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE INTERNAL "" FORCE)" to the top of CMakeLists.txt.

then make sure you have all the includes and libraries copied into /usr/local/include/ and /usr/local/lib/

**Comment by eplt** [comment]
How did you install brotli? brew install brotli?

Check if you have the following folders:
/usr/local/include/
/usr/local/lib/

If you don't have it, you might want to create it and copy over the brotli related files.

sudo mkdir /usr/local/include/
sudo mkdir /usr/local/lib/
 
sudo cp -r /opt/homebrew/include/brotli /usr/local/include/.
sudo cp -r /opt/homebrew/lib/libbrotli* /usr/local/lib/.

**Comment by chaunsin** [comment]
> 请问一下，这个错误该如何解决？ $ go install
> 
> # github.com/google/brotli/go/cbrotli
> ../../../go/pkg/mod/github.com/google/brotli/go/[cbrotli@v0.0.0-20240715182736-39bcecf4559f](mailto:cbrotli@v0.0.0-20240715182736-39bcecf4559f)/reader.go:13:10: fatal error: brotli/decode.h: No such file or directory 13 | #include <brotli/decode.h> | ^~~~~~~~~~~~~~~~~ compilation terminated.

问题解决了么,没啥问题我close了。
