### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by 1955782864** [chaunsin/netease-cloud-music#2]
一直卡在一个位置
![Screenshot_2024-08-26-09-33-39-919_com server auditor ssh client-edit](https://github.com/user-attachments/assets/56fa3cbc-629d-42c4-bf50-b1bf2e09b172)

**Comment by chaunsin** [comment]
这说明服务已经运行了，task相当于启动一个定时任务服务，只要不退出终端服务会一直在后台运行，为啥没有执行相关任务，定时任务还没有到时间所以没执行。
