### ISSUE TITLE
大佬考虑部署到docker和支持多账号吗

### ISSUE THREAD

**Issue by huakair** [chaunsin/netease-cloud-music#3]

**Comment by chaunsin** [comment]
目前暂不考虑多账号，不过想实现多账号还是可以个为每个账户维护一个配置文件的(配置信息需要保证账号之间隔离)，每个账号执行时指定对应得配置文件即可，配置文件详情: https://github.com/chaunsin/netease-cloud-music/blob/master/config/config.yaml 

至于docker部署最近抽时间我弄一下,到时候通知。

**Comment by chaunsin** [comment]
最新代码已经支持了docker部署方式。
