### ISSUE TITLE
音乐合伙人新任务

### ISSUE THREAD

**Issue by BanqiJane** [chaunsin/netease-cloud-music#5]
新任务是可以无限刷歌每首歌1分
新加了一个推荐歌曲功能 推荐全部18分
大佬有相关接口吗 或者考虑后续开发吗

**Comment by chaunsin** [comment]
如果有相关得接口实现或参考欢迎提供！

**Comment by tvcbuv** [comment]
大佬，docker考虑过添加一个web界面以方便执行命令吗

**Comment by chaunsin** [comment]
> 大佬，docker考虑过添加一个web界面以方便执行命令吗

这个暂时不考虑.不过你还是可以使用docker命令去执行命令得,可以参考连接中示例部分：https://hub.docker.com/r/chaunsin/ncmctl

**Comment by chaunsin** [comment]
> 新任务是可以无限刷歌每首歌1分 新加了一个推荐歌曲功能 推荐全部18分 大佬有相关接口吗 或者考虑后续开发吗

目前已经实现额外得歌曲测评(基本歌曲5首之外)，额外歌曲测评随机数量为2到7首歌曲，之所以这么做避免被风控。

我先关了这个issue有问题在打开。
