### ISSUE TITLE
装在docker下的一些问题

### ISSUE THREAD

**Issue by chowtaifookk** [chaunsin/netease-cloud-music#9]
大佬请问装在docker下的话需要每天都要手动执行吗 还是默认有定时时间
如果要修改每天执行时间要怎么样去操作

**Comment by chowtaifookk** [comment]
[sign] task register
[scrobble] task register
2024/12/05 08:35:06 ncmctl run directory: /app/ncmctl

到这就没有反馈了 这算运行成功了吗

**Comment by chaunsin** [comment]
@chowtaifookk 这已经运行成功了，到点了就会执行，task命令里面内置了`corntab`。如果想更改时间，可以启动时指定参数，
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/6139f491-9353-4bd0-8d1a-37c288bc42d2">

**Comment by chowtaifookk** [comment]
> @chowtaifookk 这已经运行成功了，到点了就会执行，task命令里面内置了。如果想更改时间，可以启动时指定参数，`corntab` <img alt="图像" width="1001" src="https://private-user-images.githubusercontent.com/33649884/392786283-6139f491-9353-4bd0-8d1a-37c288bc42d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTUwMzAsIm5iZiI6MTczMzQxNDczMCwicGF0aCI6Ii8zMzY0OTg4NC8zOTI3ODYyODMtNjEzOWY0OTEtOTM1My00YmQwLThkMWEtMzdjMjg4YmM0MmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE2MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZDFjNmQ5YmRkMWQ0NTczY2RjNzU2ZDY4ZDViNTI3NDVjZTVjYmViNjY0MzQxNDVlZDA1MmMwNzc4NTU5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xzzd1gPMzy-HGU9Hnxb_nrFadO5StwT8eNugEGt3aVA">

好的,谢谢大佬
